feat/medium
fivechjr/thinc-www pull request #76
Opened 2021-10-16 11:03 UTC by new5558

### Closes #70 
### Demo: https://thinc-www-ihdi0cptz-new17353.vercel.app/ (edited)

![image](https://user-images.githubusercontent.com/12471844/137584907-fc0606d2-6e20-415b-a095-2dc150fd943c.png)
![image](https://user-images.githubusercontent.com/12471844/137584930-2fe3b216-f15a-4478-a6ff-795f27908bd5.png)

2021-10-16 11:22 UTC, bombnp commented
pls use `fixes #70` or `closes #70` my man

2021-10-16 11:30 UTC, bombnp requested changes

2021-10-16 11:30 UTC, bombnp commented on .gitignore
> +.vercel
duplicate gitignore?

2021-10-16 11:30 UTC, bombnp commented on components/sections/medium.jsx
> +                    by using IT development.
```suggestion
                    using IT development.
```

2021-10-16 11:30 UTC, bombnp commented on components/sections/medium.jsx
> +                className="inline-block mx-2 mt-6"
increase margin top of all publications button a bit. probably twice as much

2021-10-16 11:30 UTC, bombnp commented on components/sections/medium.jsx
> +                </div>
should we extract this component? we can reuse it multiple time already

2021-10-16 11:30 UTC, bombnp commented on pages/index.jsx
> +export async function getStaticProps() {
does github pages support SSR?

2021-10-16 11:30 UTC, bombnp commented on components/sections/medium.jsx
> +        </a>
can we also show the first multiple lines of body of article? to know what it's about

2021-10-16 14:28 UTC, new5558 commented on pages/index.jsx
> +export async function getStaticProps() {
It is static site generator not SSR

2021-10-16 14:29 UTC, new5558 commented on components/sections/medium.jsx
> +                    by using IT development.
Should we also change this sentence on Thinc. medium website?

2021-10-16 14:32 UTC, new5558 commented on components/sections/medium.jsx
> +        </a>
![image](https://user-images.githubusercontent.com/12471844/137591431-be52c60b-7f57-42fc-ac03-825dee0c5e44.png)
I will implement it like this then.

2021-10-16 14:41 UTC, new5558 commented on pages/index.jsx
> +export async function getStaticProps() {
As we discussed in #70. We may need to run action as a cronjob/action to built a static site from medium API

2021-10-16 14:42 UTC, bombnp commented on components/sections/medium.jsx
> +                    by using IT development.
yes

2021-10-16 14:42 UTC, bombnp commented on components/sections/medium.jsx
> +                    by using IT development.
`by` is redundant

2021-10-16 14:42 UTC, bombnp commented on pages/index.jsx
> +export async function getStaticProps() {
can you open issue for this? so we don't forget to make a cron

2021-10-16 15:07 UTC, new5558 commented on components/sections/medium.jsx
> +        </a>
![image](https://user-images.githubusercontent.com/12471844/137592450-71bd9dcf-3f9f-45fb-afdf-99fc96ff5d36.png)
Done! here is a the preview

2021-10-16 15:12 UTC, new5558 commented on components/sections/medium.jsx
> +                    by using IT development.
I don't have access to Thinc. medium/ can you do it @bombnp?

2021-10-16 15:17 UTC, bombnp commented on components/sections/medium.jsx
> +                    by using IT development.
I don't. I have no idea who is owner. Even P'Far doesn't i think

2021-10-16 15:17 UTC, bombnp commented on components/sections/medium.jsx
> +        </a>
Neat

2021-10-16 15:18 UTC, bombnp commented
Can u redeploy to vercel

2021-10-16 15:20 UTC, new5558 commented
> Can u redeploy to vercel

Deployed. Check out new deployment on PR description above!

2021-10-17 03:38 UTC, bombnp commented
i feel like medium and member section should have different bg color, like the ones in team, project, and about

2021-10-17 03:38 UTC, bombnp commented
other than that, LGTM

2021-10-17 11:14 UTC, new5558 commented
> i feel like medium and member section should have different bg color, like the ones in team, project, and about

After careful selection, I decided to put change the background of the member section to be contrasted with the medium section's.
I also added a gray border in Thinc. medium description as attached image
![image](https://user-images.githubusercontent.com/12471844/137624943-dcaf5c01-8fb6-4ba8-917a-e37cc8d9c6f1.png)
![image](https://user-images.githubusercontent.com/12471844/137624960-439d16ef-0f5d-4319-8307-4dec73e79a48.png)
![image](https://user-images.githubusercontent.com/12471844/137624969-20d182bc-29ee-4afd-ba8f-135f2905ca0f.png)

2021-10-17 11:18 UTC, merged