Feature: Linktree portal
fivechjr/thinc-www pull request #83
Opened 2022-08-16 17:29 UTC by betich

2022-08-16 17:31 UTC, betich commented
<img width="882" alt="image" src="https://user-images.githubusercontent.com/28398789/184942238-6fc54748-c4b7-4cd8-9ef8-dc73c02032b8.png">

airtable backend, will polish fetch result later

2022-08-17 02:34 UTC, bombnp requested changes

2022-08-17 02:34 UTC, bombnp commented on src/pages/links.tsx
> +  const linkRecords: { href: string; Title: string }[] = (await res.json()).records.map(
I think we can use `ILinkRecord` here instead of `{ href: string; Title: string }`, just need to rename `Title` -> `title`

2022-08-17 02:34 UTC, bombnp commented on src/pages/links.tsx
> +    (record: { id: string; createdTime: string; fields: ILinkRecord }) => record.fields
Extract this type definition into its own defined interface for readability, something like `AirtableRecord`

2022-08-17 02:35 UTC, bombnp commented
also, can u post demo screenshot here in the PR as well? ty kub

2022-08-17 02:53 UTC, betich commented
demo screenshot

![image](https://user-images.githubusercontent.com/28398789/185024245-84e897d6-b149-4eef-a5d9-baeadb7b09a7.png)

2022-08-17 03:40 UTC, betich commented
done, please check again kub

2022-08-17 07:09 UTC, saenyakorn commented
Can you add app's icon for each card? For decoration

2022-08-26 03:57 UTC, betich commented
@saenyakorn imo since this will host a wide variety of links (ex. registration), we might not be able to provide an icon for some records.

wbu?

<img width="835" alt="image" src="https://user-images.githubusercontent.com/28398789/186813860-5ed23297-37b1-4c45-801e-536f1c7a7e76.png">

2022-08-26 04:02 UTC, betich commented
@bombnp review again pls

2022-08-27 05:00 UTC, bombnp commented
> @saenyakorn imo since this will host a wide variety of links (ex. registration), we might not be able to provide an icon for some records.
> 
> what do you think?
> 
> <img alt="image" width="835" src="https://user-images.githubusercontent.com/28398789/186813860-5ed23297-37b1-4c45-801e-536f1c7a7e76.png">

i still think it should have icons tho. Just add an attachment field in airtable for icon file, and don't render the icon if the icon does not exist.

2022-08-28 08:33 UTC, betich commented
done

<img width="923" alt="image" src="https://user-images.githubusercontent.com/28398789/187065189-2e1a6773-cd23-42e9-a232-ad72106c996a.png">

2022-08-28 08:44 UTC, betich commented
@bombnp reviewwwwwwwwwwww

2022-08-28 09:41 UTC, bombnp approved these changes
i'd say use colored icons, but other than that, LGTM

2022-08-28 10:13 UTC, betich commented
added coloured icons

2022-08-28 10:16 UTC, betich commented
![Uploading image.png…]()

2022-08-28 10:16 UTC, betich commented
@bombnp merge loey

2022-08-28 10:31 UTC, merged